spring:
  profiles:
    active: dev
    include: secret
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
          google:
            scope:
              - email
              - profile
            client-name: Google
            client-id: 946471835109-5ervi8ebhdp735ukt05q382qqoj34rg1.apps.googleusercontent.com
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
          naver:
            client-id: A8wH_WMXKUDEEGNenGZA
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/naver'
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  mail:
    host: smtp.gmail.com
    port: 587
    username: 20182548@edu.hanbat.ac.kr
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100 # Lazy 로딩 시, 한번에 가져올 DB 엔티티 개수 설정
        show_sql: true # SQL 쿼리를 로그에 출력
        format_sql: true # SQL 쿼리를 포맷팅하여 보기 좋게 출력
        use_sql_comments: true # SQL 쿼리 주석 사용
    logging:
    level:
      # SQL 쿼리를 디버깅하고, SQL 파라미터를 추적하고 추출할 때의 로깅 레벨 설정
      org.hibernate.SQL: DEBUG
      org.hibernate.orm.jdbc.bind: TRACE
      org.hibernate.orm.jdbc.extract: TRACE
      org.springframework.transaction.interceptor: TRACE
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB